---

- name: "Configuring Banners"
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all

  tasks:

  - name: Configure the login banner
    cisco.ios.ios_banner:
      banner: login
      text: |
        This is brandons banner
        string
      state: present
